print ("---- MENU ----")
print ("[1.] Menambah Data Mahasiswa")
print ("[2.] Mengubah Data Mahasiswa")
print ("[4.] Mengapus Data Mahasiswa ")
print ("[4.] Melihat Seluruh Data Mahasiswa")
print ("[4.] Keluar")
pilih = input("pilih : ")